grocery_shopping/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # include() works like an import of URLs.
    path('users/', include('users.urls')),
    path('', include('shopping_registry.urls')),
]

shopping_registry/urls.py
"""Defines URL patters for Grocery Registry"""

from django.urls import path

from . import views

app_name = 'shopping_registry'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that displays instructions and links to the new_product view.
    path('instrucciones/registro', views.registering_instructions, 
        name='registering_instructions'),
    # Page that displays instructions for the use of the demo account.
    path('instrucciones/demo', views.demo_account_instructions, 
        name='demo_instructions'),
    # Page that shows all purchases.
    path('dates/', views.dates, name="dates"),
    # Detail page for a single date.
    path(r'dates/(<date>\d{4}-\d{2}-\d{2})/', views.date, name='date'),
    # Page for adding a new purchase.
    path('registrar_compra/', views.new_purchase, name='new_purchase'),
    # Page for editing a purchase.
    path('editar/compra/<int:purchase_id>', views.edit_purchase, 
        name='edit_purchase'),
    # Page to confirm the deletion of a single date.
    path(r'confirmar/borrar/(<date_string>\d{4}-\d{2}-\d{2})/', views.erase_date_confirmation, 
        name='erase_date_confirmation'),
    # Page to confirm the deletion of a single purchase.
    path('confirmar/compra/<int:purchase_id>', views.delete_purchase_confirmation, 
        name='delete_purchase_confirmation'),
    # Page for deleting all the purchases made on the selected date.
    path(r'borrar/(<date_string>\d{4}-\d{2}-\d{2})/', views.erase_date, name='erase_date'),
    # Page for deleting a single purchase.
    path('borrar/compra/<int:purchase_id>', views.delete_purchase, 
        name='delete_purchase'),
    # Page that displays all years with registered purchases.
    path('years/', views.Years, name='years'),
    # Page that displays the months in a year.
    path('<int:year>/', views.Months, name='months'),
    # Detail page for a month's shopping trips.
    # Example: /2021/12/
    path('<int:year>/<int:month>/', views.MonthView, name='MonthView'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration  page.
    path('register/', views.register, name='register'),
]

shopping_registry/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

class Purchase(models.Model):
    """The purchase of a product."""
    product = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    date_purchase = models.DateField()
    # Compras a granel / Bulk purchases
    bulk = models.BooleanField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)

    class Meta:
        verbose_name_plural = 'purchases'

    def __str__(self):
        """Return a string representation of the purchase."""
        if self.bulk == True:
            if self.quantity >= 1000:
                return f"{(self.quantity / 1000)} kilo/s de {self.product} por ${self.price}"
            else:
                return f"{self.quantity} gramos de {self.product} por ${self.price}"
        else:
            return f"{self.quantity} de {self.product} por ${self.price}"

shopping_registry/forms.py
from django import forms

from .models import Purchase

class PurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = ['product', 'category', 'quantity', 'price', 'date_purchase', 'bulk']
        labels = {'product': 'Producto','category': 'Categoria', 'quantity': 'Cantidad', 'price': 'Precio',
            'date_purchase': 'Fecha de compra', 'bulk': 'Granel'}

shopping_registry/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.core import serializers
from django.db.models import Sum

from shopping_registry import accountVerification
from shopping_registry import totalCalculations
from shopping_registry import graphGeneration

from .models import Purchase
from .forms import PurchaseForm

import json
import datetime 

def index(request):
    """The home page for Registro-Super."""
    return render(request, 'shopping_registry/index.html')

@login_required
def dates(request):
    """Shows all dates."""
    dates = []

    purchases = Purchase.objects.filter(owner=request.user).order_by('-date_purchase')

    for purchase in purchases:
        if purchase.date_purchase not in dates:
            dates.append(purchase.date_purchase)

    context = {'dates': dates}
    return render(request, 'shopping_registry/dates.html', context)

@login_required
def date(request, date):
    """Shows all the information for a day's purchases."""
    
    date_string = date
    date = datetime.datetime.strptime(date, '%Y-%m-%d')
    
    purchases = Purchase.objects.filter(date_purchase=date, owner=request.user)

    total = totalCalculations.calculate_total(purchases)

    products = []

    quantities = []

    prices = []

    ind_prices = [] 

    # Stores the name of the product, its individual price and its bulk's boolean
    # value
    dictionary = {}

    categories = []

    categories_total = totalCalculations.total_categories(purchases)

    bulk = []

    for purchase in purchases:
        products.append(purchase.product)
        quantities.append(purchase.quantity)
        prices.append(purchase.price)
        bulk.append(purchase.bulk)

    for x in range(0, len(products)):
        if purchases[x].category.title() not in categories:
            categories.append(purchases[x].category.title())

        if bulk[x] == True:
            # If it was a bulk purchase, multiply by 100 to display the price per
            # 100 grams.
            ind_prices.append(float((prices[x] / quantities[x]) * 100))
        else:
            ind_prices.append(float((prices[x] / quantities[x])))

        ind_prices[x] = round(ind_prices[x], 2)

        dictionary[x] = {'Nombre': purchases[x], 'Categoria': purchases[x].category,
            'Bulk': bulk[x], 'Precio': ind_prices[x]}


    # Product and Price visualization

    # Convert the prices list QuerySet to a list of floats.
    prices_float = [float(price) for price in prices]

    # Generating the charts.
    # Bar chart.
    bar_graph = graphGeneration.generateBarGraph(products, prices_float)

    # Pie chart.
    pie_graph = graphGeneration.generatePieGraph(categories_total)

    context = {'date': date, 'date_string': date_string, 'purchases': purchases, 'total':total, 
        'products':products, 'ind_prices':ind_prices, 'dictionary': dictionary,
        'categories': categories, 'categories_total': categories_total, 
        'bar_graph': bar_graph, 'pie_graph': pie_graph}
    return render(request, 'shopping_registry/date.html', context)

@login_required
def edit_purchase(request, purchase_id):
    """Edit an existing purchase."""
    purchase = get_object_or_404(Purchase, id=purchase_id)

    # Checks if user is using demo account and is the owner of the object.
    accountVerification.check_account(request.user.username, purchase)

    date = purchase.date_purchase

    # Passes the data to the form template.
    formatedDate = date.strftime("%m/%d/%Y")

    initial_dict = {
        "date_purchase" : formatedDate,
        "bulk": True,
    }

    if request.method != 'POST':
        # Initial request; pre-fill form with the current purchase.
        form = PurchaseForm(instance=purchase, initial=initial_dict)
    else:
        # POST data submitted; process data.
        form = PurchaseForm(data=request.POST, instance=purchase)

        if form.is_valid():
            edited_purchase = form.save(commit=False)
            edited_purchase.owner = request.user
            edited_purchase.save()
            return redirect('shopping_registry:date', date=date)

    context = {'purchase': purchase, 'form': form, 'date': formatedDate}
    return render(request, 'shopping_registry/edit_purchase.html', context)

@login_required
def erase_date_confirmation(request, date_string):
    """Confirm the deletion of the purchases done on the selected date."""

    accountVerification.check_account(request.user.username)

    purchases = Purchase.objects.filter(date_purchase=date_string, owner=request.user)

    # Date is stored in string 'YYYY-MM-DD', converted to datetime value.
    date = datetime.datetime.strptime(date_string, '%Y-%m-%d')

    context = {'date': date, 'purchases': purchases, 'date_string': date_string}
    return render(request, 'shopping_registry/erase_date_confirmation.html', context)

@login_required
def erase_date(request, date_string):
    """Delete all the purchases done on the selected date."""

    accountVerification.check_account(request.user.username)

    # Date_string is stored in string format 'YYYY-MM-DD', 
    # converted to datetime value.
    date = datetime.datetime.strptime(date_string, '%Y-%m-%d')

    purchases = Purchase.objects.filter(date_purchase=date_string, owner=request.user)

    purchases_erase = purchases.delete()

    context = {'date': date, 'purchase': purchases}
    return render(request, 'shopping_registry/erase_date.html', context)

@login_required
def delete_purchase_confirmation(request, purchase_id):
    """Confirms the deletion of a purchase."""
    purchase = get_object_or_404(Purchase, id=purchase_id)

    accountVerification.check_account(request.user.username, purchase)

    context = {'purchase': purchase}
    return render(request, 'shopping_registry/delete_purchase_confirmation.html', 
        context)    

@login_required
def delete_purchase(request, purchase_id):
    """Deletes a single purchase."""
    purchase = get_object_or_404(Purchase, id=purchase_id)

    accountVerification.check_account(request.user.username, purchase)

    purchase_erase = purchase.delete()

    context = {'purchase': purchase}
    return render(request, 'shopping_registry/delete_purchase.html', context)

@login_required
def MonthView(request, year, month):
    """Displays all shopping trips in a month."""

    purchases = Purchase.objects.filter(date_purchase__year=year, 
        date_purchase__month=month, owner=request.user)

    total = totalCalculations.calculate_total(purchases)

    dates = []

    products_total = {}

    categories_total = totalCalculations.total_categories(purchases)

    for purchase in purchases:
        if purchase.product not in products_total:
            products_total[purchase.product] = 0
            products_total[purchase.product] += purchase.price
        else:
            products_total[purchase.product] += purchase.price

        if purchase.date_purchase not in dates:
            dates.append(purchase.date_purchase)

    date = datetime.datetime(year, month, 1)

    # Stores keys and values from dict to use as labels and values in the charts.
    # Bar chart.
    bar_labels = products_total.keys()
    bar_values = products_total.values()

    # Casts into list for chart compatibility.
    # Bar chart.
    bar_labels = list(bar_labels)
    bar_values = list(bar_values)

    # Generating the charts.
    # Bar chart.
    bar_graph = graphGeneration.generateBarGraph(bar_labels, bar_values)

    # Pie chart.
    pie_graph = graphGeneration.generatePieGraph(categories_total)

    context = {'date': date, 'dates': dates, 'total':total, 
        'products_total': products_total, 'categories_total': categories_total,
        'bar_graph': bar_graph, 'pie_graph':pie_graph}
    return render(request, 'shopping_registry/month_view.html', context)

@login_required
def Years(request):
    """Shows all years with registered purchases."""

    purchases = Purchase.objects.filter(owner=request.user).order_by('date_purchase')

    years = []
    for purchase in purchases:
        if purchase.date_purchase.year not in years:
            years.append(purchase.date_purchase.year)
    context = {'years': years}
    return render(request, 'shopping_registry/years.html', context)

@login_required
def Months(request, year):
    """Shows all the months with registered purchases in the selected month."""
    purchases = Purchase.objects.filter(owner=request.user).order_by('date_purchase')

    months = []
    for purchase in purchases:
        if purchase.date_purchase.month not in months:
            months.append(purchase.date_purchase.month)

    datetimes = []
    for month in months:
        datetimes.append(datetime.datetime(year, month, 1).date())

    context = {'months': months, 'dates': datetimes, 'year': year}
    return render(request, 'shopping_registry/months.html', context)

@login_required
def registering_instructions(request):
    """Page that links to the PurchaseForm and includes instructions."""

    accountVerification.check_account(request.user.username)

    return render(request, 'shopping_registry/instrucciones_registro.html')

def demo_account_instructions(request):
    """Page that links to the log-in form and includes instructions regarding the
    use of the demo account."""

    return render(request, 'shopping_registry/instrucciones_demostracion.html')

@login_required
def new_purchase(request):
    """Add a new purchase."""
    username = request.user.username
    accountVerification.check_account(username)

    next = redirect('shopping_registry:dates')

    print("this works")

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = PurchaseForm()
    else:
        # POST data submitted; process data.
        form = PurchaseForm(data=request.POST)
        if form.is_valid():

shopping_registry/templates/shopping_registry/date.html
{% extends 'shopping_registry/base.html' %}

{% block page_header %}
<h1 class="display-2">
    <div class="text-center fw-bold">
        {{ date|date:"j N Y" }}
    </div>
</h1>
{% endblock page_header %}

{% block content %}
<!-- Buttons with functions related to the date. -->
<div class="d-grid gap-2 d-md-block text-center btn-group btn-group-sm" role="group" aria-label="Function buttons">
    <a href="{% url 'shopping_registry:erase_date_confirmation' date_string %}" class="btn btn-danger" role="button">
        Eliminar fecha
    </a>
    <a href="{% url 'shopping_registry:new_purchase' %}" class="btn btn-primary" role="button">
        Registrar compra
    </a>
</div>

<!-- Displays the total spent in the selected date. -->
<br>
<div class="bd-heading align-self-start mb-3 mt-x1-0 mb-x1-2">
    <h3>
        Gasto total:
    </h3>
</div>
<h1 class="display-5">
    <div class="text-center">
        ${{ total }}
    </div>
</h1>

<!-- The purchases linked to the date. -->
<br>
<div class="bd-heading align-self-start mb-3 mt-x1-0 mb-x1-2">
    <h3>
        Compras:
    </h3>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">
                Producto
            </th>
            <th scope="col">
                Cantidad
            </th>
            <th scope="col">
                Total
            </th>
            <th>
                
            </th>
        </tr>
    </thead>
    <tbody>
        {% for purchase in purchases %}
        <tr>
            <td>
                {{ purchase.product }}
            </td>
            <td>
                {% if purchase.bulk == True %}
                    {{ purchase.quantity }} gr.
                {% else %}
                    {{ purchase.quantity }}
                {% endif %}
            </td>
            <td>
                ${{ purchase.price }}
            </td>
            <td>
                <a href="{% url 'shopping_registry:edit_purchase' purchase.id %}"
                    class="btn btn-secondary" role="button">
                    Editar
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Table to display the total spent per category of products. -->
<br>
<div class="bd-heading align-self-start mb-3 mt-x1-0 mb-x1-2">
    <h3>
        Gasto por categoría:
    </h3>
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">
                Categoría
            </th>
            <th scope="col">
                Total
            </th>
        </tr>
    </thead>
    <tbody>
        {% for category, total in category_spent.items %}
        <tr>
            <td>
                {{ category }}
            </td>
            <td>
                ${{ total }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Individual prices for products. -->
<br>
<div class="bd-heading align-self-start mb-3 mt-x1-0 mb-x1-2">
    <h3>
        Costo p/unidad o 100 gramos:
    </h3>
</div>

{% for key, value in dictionary.items %}
    <div class="card" style="width: 18rem; text-align:center; width: 300px;
        margin: 0 auto;">
        <ul class="list-group list-group-flush">
    {% for key2, value2 in value.items %}
        <!-- Checks for bulk value. -->
        {% if value2 == True %}
            <li class="list-group-item">
                Precio p/100 gramos:
        {% elif value2 == False %}
            <li class="list-group-item">
                Precio p/unidad:
        <!-- Checks if the value is the price. -->
        {% elif value2 > 0 %}
                ${{ value2 }}
            </li>
        <!-- Checks if the value is the category name. -->
        {% elif value2 in categories %}
            <li class="list-group-item">
                Categoria: {{ value2 }}
            </li>
        <!-- The product name. -->
        {% else %}
            <div class="card-header">
                <b>
                    {{ value2 }}
                </b>
            </div>
        {% endif %}
    {% endfor %}
        </ul>
    </div>
    <br>
{% empty %}
    <h1>
        Aun no se han registrado productos.
    </h1>
{% endfor %}

<!-- Graphs for the date's products. -->
<br>
<div class="bd-heading align-self-start mb-3 mt-x1-0 mb-x1-2">
    <h3>
        Gasto total por producto:
    </h3>
</div>
<p>
    {% if bar_graph %}
    <div style="width:600; height:500;">
        {{ bar_graph|safe}}
    </div>
    {% endif %}
</p>

<!-- Graph for total spent per category. -->
<br>
<div class="bd-heading align-self-start mb-3 mt-x1-0 mb-x1-2">
    <h3>
        Gasto total por categoría
    </h3>
</div>
<p>
    {% if pie_graph %}
    <div style="width:600; height:500;">
        {{ pie_graph|safe}}
    </div>
    {% else %}
    <p>
        No graph was provided.
    </p>
    {% endif %}
</p>

{% endblock content %}

shopping_registry/templates/shopping_registry/delete_purchase.html
{% extends "shopping_registry/base.html" %}

{% block page_header %}
<h1 class="display-5">
    <div class="text-center fw-bold">
        Compra eliminada
    </div>
</h1>
{% endblock page_header %}

{% block content %}

<h1>
    La compra {{ purchase }} ha sido eliminada.
</h1>

{% endblock content %}

shopping_registry/templates/shopping_registry/delete_purchase_confirmation.html
{% extends "shopping_registry/base.html" %}

{% block page_header %}
<h1 class="display-5">
    <div class="text-center fw-bold">
        ¡Lea con atención!
    </div>
</h1>
{% endblock page_header %}

{% block content %}

<h2>Esta tratando de borrar la compra {{ purchase }}. ¿Seguro?</h2>

    <div class="d-grid gap-2 col-6 mx-auto mt-5">
        <a href="{% url 'shopping_registry:delete_purchase' purchase.id %}" 
            class="btn btn-danger btn-lg" role="button">
            Si, deseo borrar la compra.
        </a>
    </div>

{% endblock content %}

shopping_registry/templates/shopping_registry/edit_purchase.html
{% extends "shopping_registry/base.html" %}

{% block page_header %}
<h1 class="display-2">
    <div class="text-center fw-bold">
        {{ purchase }}
    </div>
</h1>
{% endblock page_header %}

{% block content %}
    <!-- Buttons with functions related to the template. -->
    <div class="d-grid gap-2 d-md-block text-center btn-group btn-group-sm mb-5" role="group" aria-label="Function buttons">
        <a href="{% url 'shopping_registry:registering_instructions' %}" class="btn btn-secondary" role="button">
            Instrucciones
        </a>
        <a href="{% url 'shopping_registry:delete_purchase_confirmation' purchase.id %}" class="btn btn-danger" role="button">
            Eliminar esta compra
        </a>
    </div>

    <!-- Form to edit the purchase. -->
    <form action="{% url 'shopping_registry:edit_purchase' purchase.id %}" method='post'>
        {% csrf_token %}

        {{ form.non_fields_errors }}

        <div class="fieldWrapper input-group mb-3">
            {{ form.product.errors }}
            <label for="{{ form.product.id_product }}" class="input-group-text">
                Producto: 
            </label>
            <input id="{{ form.product.id_product }}" type="text" 
                class="form-control" name="product" value="{{purchase.product}}" required>
        </div>

        <br>

        <div class="fieldWrapper input-group mb-3">
            {{ form.category.errors }}
            <label for="{{ form.category.id_category }}" class="input-group-text">
                Categoría: 
            </label>
            <input id="{{ form.category.id_category }}" type="text"  
            class="form-control" name="category" value="{{purchase.category}}" required>
        </div>

        <br>
        <div class="fieldWrapper input-group mb-3">
            {{ form.quantity.errors }}
            <label for="{{ form.quantity.id_quantity }}" class="input-group-text">
                Cantidad: 
            </label>
            <input id="{{ form.category.id_quantity }}" type="text"  
            class="form-control" name="quantity" value="{{purchase.quantity}}"
            placeholder="En gramos si es compra a granel" required>
        </div>

        <br>

        <div class="fieldWrapper input-group mb-3">
            {{ form.price.errors }}
            <label for="{{ form.price.id_price }}" class="input-group-text">
                Precio total: 
            </label>
            <span class="input-group-text">
                $
            </span>
            <input id="{{ form.category.id_price }}" type="text"  
            class="form-control" name="price" value="{{purchase.price}}" required>
        </div>

        <br>

        <div class="fieldWrapper input-group mb-3">
            {{ form.date_purchase.errors }}
            <label for="{{ form.date_purchase.id_date_purchase }}" class="input-group-text">
                Fecha de la compra:
            </label>
            <input id="id_date_purchase" type="text"  
            class="form-control" name="date_purchase" placeholder="MM/DD/AAAA" 
            value="{{ date }}" required>
        </div>

        <br>

        <div class="fieldWrapper input-group mb-3">
            {{ form.bulk.errors }}
            <label for="{{ form.bulk.id_bulk }}" class="input-group-text">
                Llena la casilla si fue compra a granel: 
            </label>
            <div class="input-group-text">
                {% if purchase.bulk == True %}
                <input type="checkbox" name="bulk" id="id_bulk" 
                    class="form-check-input" checked>
                {% else %}
                <input type="checkbox" name="bulk" id="id_bulk" 
                    class="form-check-input">
                {% endif %}
            </div>
        </div>

        <br>

        <div class="d-grid gap-2 d-md-block text-center btn-group btn-group-lg">
            <button name="submit" class="btn btn-success btn-lg mt-5">
                Guardar cambios
            </button>
        </div>
        
    </form>    

{% endblock content %}

shopping_registry/templates/shopping_registry/erase_date_confirmation.html
{% extends "shopping_registry/base.html" %}

{% block page_header %}
<h1 class="display-5">
    <div class="text-center fw-bold">
        ¡Lea con atención!
    </div>
</h1>
{% endblock page_header %}

{% block content %}

<p class="lead">
    Esta tratando de eliminar todas las compras realizadas el día {{ date|date:"j N Y" }}. <strong>¿Seguro/a?</strong> 
</p>

<p>Esto eliminara todas las compras realizadas en esta fecha:</p>

<!-- The purchases linked to the date. -->
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">
                Producto
            </th>
            <th scope="col">
                Cantidad
            </th>
            <th scope="col">
                Total
            </th>
            <th>
                
            </th>
        </tr>
    </thead>
    <tbody>
        {% for purchase in purchases %}
        <tr>
            <td>
                {{ purchase.product }}
            </td>
            <td>
                {% if purchase.bulk == True %}
                    {{ purchase.quantity }} gr.
                {% else %}
                    {{ purchase.quantity }}
                {% endif %}
            </td>
            <td>
                ${{ purchase.price }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

    <!-- Buttons with functions related to the template. -->
    <div class="d-grid gap-2 d-md-block text-center btn-group btn-group-sm mb-5" role="group" aria-label="Function buttons">
        <a href="{% url 'shopping_registry:erase_date' date_string %}" class="btn btn-danger" role="button">
            Si, deseo borrarlas.
        </a>
        <a href="{% url 'shopping_registry:date' date_string %}" class="btn btn-secondary" role="button">
            No, quiero regresar.
        </a>
    </div>

{% endblock content %}

shopping_registry/templates/shopping_registry/index.html
{% extends "shopping_registry/base.html" %}

{% block page_header %}
<div class="px-4 py-5 my-5 text-center">
    <img src="https://i.imgur.com/LiV0Dlk.png" 
        class="d-block mx-auto mb-4" alt="banana logo" width="72" height="57">
    <h1 class="display-5 fw-bold text-center">
        Registro de compras de Súper
    </h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">
            Este programa te ayuda a registrar todas tus compras del Súper y analizar tus gastos.
        </p>
        {% if user.is_authenticated %}
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a class="btn btn-lg btn-primary px-4 gap-3" 
                href="{% url 'shopping_registry:registering_instructions' %}"
                role="button">
                Registra una compra &raquo;
            </a>            
        </div>
        {% else %}
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a class="btn btn-lg btn-primary px-4 gap-3" 
                href="{% url 'users:register' %}"
                role="button">
                Regístrate &raquo;
            </a>
            <a class="btn btn-lg btn-primary px-4 gap-3" 
                href="{% url 'shopping_registry:demo_instructions' %}">
                Demostración &raquo;
            </a>            
        </div>
        {% endif %}
    </div>
</div>
{% endblock page_header %}

shopping_registry/templates/shopping_registry/new_purchase.html
{% extends "shopping_registry/base.html" %}

{% block page_header %}
<h1 class="display-5">
    <div class="text-center fw-bold">
        Registra una nueva compra:
    </div>
</h1>
{% endblock page_header %}

{% block content %}
    <div class="d-grid gap-2 d-md-block text-center btn-group btn-group-sm mb-5" 
        role="group" aria-label="Function buttons">
        <a href="{% url 'shopping_registry:registering_instructions' %}" 
            class="btn btn-secondary" role="button">
            Instrucciones
        </a>
    </div>
    <form action="{% url 'shopping_registry:new_purchase' %}" method='post'>
        {% csrf_token %}

        {{ form.non_fields_errors }}

        <div class="fieldWrapper input-group mb-3">
            {{ form.product.errors }}
            <label for="{{ form.product.id_product }}" class="input-group-text">
                Producto: 
            </label>
            <input id="{{ form.product.id_product }}" type="text" 
                class="form-control" name="product" placeholder="Nombre del producto" 
                required>
        </div>

        <br>

        <div class="fieldWrapper input-group mb-3">
            {{ form.category.errors }}
            <label for="{{ form.category.id_category }}" class="input-group-text">
                Categoría: 
            </label>
            <input id="{{ form.category.id_category }}" type="text"  
            class="form-control" name="category" 
            placeholder="Puede ser 'comida', 'ropa', etc." required>
        </div>

        <br>
        
        <div class="fieldWrapper input-group mb-3">
            {{ form.quantity.errors }}
            <label for="{{ form.quantity.id_quantity }}" class="input-group-text">
                Cantidad: 
            </label>
            <input id="{{ form.category.id_quantity }}" type="text"  
            class="form-control" name="quantity" 
            placeholder="En gramos si es compra a granel, 1 kilo es igual a 1000 gramos" 
            required>
        </div>

        <br>

        <div class="fieldWrapper input-group mb-3">
            {{ form.price.errors }}
            <label for="{{ form.price.id_price }}" class="input-group-text">
                Precio total: 
            </label>
            <span class="input-group-text">
                $
            </span>
            <input id="{{ form.category.id_price }}" type="text"  
            class="form-control" name="price" required>
        </div>

        <br>

        <div class="fieldWrapper input-group mb-3">
            {{ form.date_purchase.errors }}
            <label for="{{ form.date_purchase.id_date_purchase }}" class="input-group-text">
                Fecha de la compra:
            </label>
            <input id="id_date_purchase" type="text"  
            class="form-control" name="date_purchase" placeholder="MM/DD/AAAA" 
            required>
        </div>

        <br>

        <div class="fieldWrapper input-group mb-3">
            {{ form.bulk.errors }}
            <label for="{{ form.bulk.id_bulk }}" class="input-group-text">
                Llena la casilla si fue compra a granel: 
            </label>
            <div class="input-group-text">
                <input type="checkbox" name="bulk" id="id_bulk" 
                    class="form-check-input">
            </div>
        </div>

        <br>

        <div class="d-grid gap-2 d-md-block text-center btn-group" role="group" 
            aria-label="Function buttons">
            <button name="submit" class="btn btn-success btn-lg mt-5">
                Registrar compra
            </button>
            <button name="saveAnother" type="submit" 
            class="btn btn-success btn-lg mt-5" value="saveAnother">
                Guardar y registrar otra
            </button>
            <a class="btn btn-danger btn-lg mt-5" href="{% url 'shopping_registry:index' %}">
                Cancelar
            </a>
        </div>

    </form>
{% endblock content %}